export enum ErrorsEnum {
  SERVER_ERROR = 'serverError',
  TIME_OUT_ERROR = 'timeOutError',
  NOT_FOUND_ERROR = 'notFoundError',
  MIDDLEWARE_ERROR = 'middlewareError',
  INVALID_CPF_ERROR = 'invalidCpfError',
  UNAVAILABLE_ERROR = 'unavailableError',
  MICROSERVICE_ERROR = 'microserviceError',
  UNAUTHORIZED_ERROR = 'unauthorizedError',
  INVALID_PHONE_ERROR = 'invalidPhoneError',
  INVALID_ROUTE_ERROR = 'invalidRouteError',
  MISSING_PARAM_ERROR = 'missingParamError',
  INVALID_PARAM_ERROR = 'invalidParamError',
  NOT_FOUND_USER_ERROR = 'notFoundUserError',
  NOT_FOUND_ROUTE_ERROR = 'notFoundRouteError',
  HASHER_PASSWORD_ERROR = 'hasherPasswordError',
  DATABASE_CONNECT_ERROR = 'datbaseConnectError',
  EMAIL_ALREADY_REGISTERED = 'emailAlreadyRegistered',
  INTEGRATION_HUB_API_ERROR = 'integrationHubApiError',
  INVALID_VALUE_IN_ENUMERABLE_ERROR = 'invalidValueInEnumerableError'
}
